project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!R/"

website:
  title: "lidRtutorial"
  favicon: "images/favicon/apple-touch-icon.png"
  site-url: https://r-lidar.github.io/lidRbook/
  navbar:
    search: true
    background: light
    collapse-below: lg
    type: light
    logo: "img/logo.png"
    left:
      - text: "1-INTRO"
        href: "01_intro.qmd"
      - text: "2-LAS"
        href: "02_read.qmd"
      - text: "3-CLASSIFICATION"
        href: "03_classification.qmd"
      - text: "4-DTM"
        href: "04_dtm.qmd"
      - text: "5-CHM"
        href: "05_chm.qmd"
      - text: "6-METRICS"
        href: "06_metrics.qmd"
      - text: "7-LASCATALOG"
        href: "07_engine.qmd"
      - text: "8-SOLUTIONS"
        href: "08_solutions.qmd"
      - text: "SUPPLEMENTAL"
        menu:
          - text: "ROI"
            href: "supplemental/S1_roi.qmd"
          - text: "ABA"
            href: "supplemental/S2_aba.qmd"
          - text: "ITS"
            href: "supplemental/S3_its.qmd"
          - text: "ENGINE"
            href: "supplemental/S4_engine2.qmd"
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: [simple, assets/styles.scss]
    css: [assets/custom.css]
    toc: true
    toc-depth: 4
    code-overflow: wrap

editor: visual